### ISSUE TITLE
Discussion: Remove PrivacyTools?

### ISSUE THREAD

**Issue by NobodySpecial256** [NobodySpecial256/thgtoa#61]
PrivacyTools.io recently seems to be controversial with regard to claims of [just being affiliate links and FUD](https://github.com/NobodySpecial256/thgtoa/pull/59#issuecomment-1168628032). I'm creating this issue to allow people to provide their thoughts and reach a decision regarding this.

**Comment by blacklight447** [comment]
Just hoping in here ( disclosure, im part of the privacyguides team) but it seems that your link talks about privacytools.io doing affiliate links, not us.

We don't do affiliate links and all donations are transparently listed on opencollective :)

**Comment by blacklight447** [comment]
I must say that the feelings of some team members should not be taken as the viewpoint of the project. If something is our official view, then it would be listed on the website.

Tommy is a relatively new junior member at the team, he has quite a "fiery passion' for his opinion indeed. ill have a talk with him about it. 

Please let me know if you have any other complaints :)

**Comment by NobodySpecial256** [comment]
> Just hoping in here ( disclosure, im part of the privacyguides team) but it seems that your link talks about privacytools.io doing affiliate links, not us.

I thought PrivacyGuides was just the new name for PrivacyTools? Are they actually separate organizations?

**Comment by thanharrison** [comment]
This didn't necessarily need a Issue to itself, but only because I believe there's a place and time for discussion of Matrix problems. I will explain my travels on Matrix and give context to the issue. Day before last, I got onto the Matrix space and joined the chat in Privacy Guides, Cybersecurity general and both of the Off-Topic chats, respectively. I began seeing people discussing cryptography and signals in terms of higher threat models and so we began discussing the topic of VPN over Tor and Tor over VPN, and mobile device signals intelligence gathering techniques that are usually employed by state actors and other persistent threats across the cybersecurity landscape. 

I began to explain about different types of things that say, Mossad, or the IDF, or CIA/NSA might use against you that negated any encryption and personal security you may have. The person was asking about how to secure their mobile device and it was stated many times that they were using Qubes and Whonix to conceal their network traffic and to compartmentalize.

The use of VPNs and Tor came up and I thought, maybe they're trolling, maybe not, but it's important to get accurate information out there and prevent FUD. So I said that VPNs hinder your anonymity and security and that none of it matters for the most part. The Mossad agents in real life do not look anything like in the movies. The organization doesn't focus on digital forensics and cyber warfare, they focus on physical security and tradecraft. If you are being pursued by actors such as the NSA sure, they will attack your systems, but foreign international spy agencies won't worry about your encryption, they will simply needle you in your sleep. Your focus should be on personal security and opsec rather than traffic attacks and email hacking. 

So shortly into this conversation we were discussing the affect of a VPN on your anonymity and how you limit your nodes and by extension lower the safety offered by the Tor network. It was discussed how you will invariably destroy your opsec by shifting trust from your ISP to another third party ISP (of the VPN) you may not even be aware of, simply because you might "trust" this VPN provider more than the original ISP. The issue is that, in higher threat models, you need a zero-trust architecture of both your digital habits and your physical IRL security. Because the nature becomes less about your digital life and more and more physical; e.g., where you stay, whom you speak with, your addresses, your family's addresses, where you/they work, your cars security, are you alone, do you have a girlfriend or wife, kids, etc. It's about finding you based on your online profile and not trying to decrypt what you may be trying to hide in your traffic and your systems.

It's not enough to have good communications security, anti-forensics capabilities, etc. It's physical. It's still party digital defense and hardening but mostly it's your physical security that should be focused on, like strong situational awareness and preventing tracking devices and trail cars.

I left for a cup of coffee and when I came back I was told I had been banned for "trolling". This is not the first time PG has banned me for discussing real threats like this. They call us trolls and label it a LARP so they don't have to address the fact that half the people in privacy - security - anonymity circles or spaces, whatever, they don't have any idea what it means to practice good opsec. It's like every time I speak of higher threat models like global adversaries such as APTs and nation states, and how to avoid them rather than telling people to use Tor and VPNs, Tails and Whonix, throw them into Qubes and tell them good luck ... no, that's not at all what you should do with people. It can get them killed.

I use my experiences in the armed forces, my experience as an analyst, who has seen the signals monitoring capabilities of governments in the states and overseas, to show people the true way of protecting their online and physical lives, and how they are two separate entities requiring vastly different measures. It's not like we can tell people to go use Tor, read some online charts, and then everything is fine. 

These people require skills and tactics and backup by security teams to remain safe in their day-to-days. I ran security for a group of people in bad situations as a contractor before, and using Tails doesn't stop VIPs from getting hit by car bombs and roadside attacks, being gunned down at the gym, at their work, or at their kids daycare. People like that need real training and you should only be pointing them toward real options not telling them to gather some USBs and setup persistence on LUKs and hope your advice is well-met and heeded at every turn. The advice you give them can get them assassinated. What advice would you give to someone evading a nation state other than point them to private security forces with knowledge of tactics and weaponry? Cause you might be able to tell activists how to setup secure communications between individuals and organizations, as we do, but you can't teach them how to avoid physical tells, how to avoid tracking devices and where to look for bombs, wires, and other electronic means of maiming and injuring with the goal of incapacitating you when you're not paying attention. Leave that to professional security forces.

That's probably when I was banned. Idk, it was never clarified and I don't care at this point If we can't discuss real threats then what is the point? We're all here to advise people digitally not physically. I can tell you how to avoid being targeted by Mossad by then if you're caught, it's not something anybody can help you with. Same goes for CIA, IDF, German special police, and other "discretionary tactics" groups that know how to find people. 

I am aware it may sound like someone with this knowledge is LARPing or trolling, but I assure you it's a very serious topic.

**Comment by NobodySpecial256** [comment]
It seems like it's decided. We'll remove PTIO from the guide
